### ISSUE TITLE
Example project code fails to run with Jest 28

### ISSUE THREAD

**Issue by Juraj-Masiar** [Lusito/mockzilla-webextension#14]
Hello,

I'm trying to upgrade to jest 28 but I can't make it work.
I've created a new blank project with minimum libraries but the test fails in the "chalk" library, maybe it needs update? Or why is it even trying to use import inside a function, it just doesn't make sense.

This is the full error log:
```
C:\Users\juraj\git\addons\_bugzilla\mockzilla>npx jest
 FAIL  ./some.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    C:\Users\juraj\git\addons\_bugzilla\mockzilla\node_modules\chalk\source\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import ansiStyles from '#ansi-styles';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (node_modules/mockzilla/dist/node.js:7:33)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.403 s
Ran all test suites.
```

The minimal example project:
[mockzilla.zip](https://github.com/Lusito/mockzilla-webextension/files/9101900/mockzilla.zip)

Thank you!

**Comment by Juraj-Masiar** [comment]
Or maybe the Chalk needs downgrade, as I'm looking at their npm page:
> IMPORTANT: Chalk 5 is ESM. If you want to use Chalk with TypeScript or a build tool, you will probably want to use Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
